# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2Ka4N-owxhjg1bmrsx7bi51ILv-XWl1
"""

print("Write down all your data pre processing steps here")